"""JAX-native monoenergetic neoclassical transport solver."""

from importlib.metadata import PackageNotFoundError, version

from .autodiff import (
    BootstrapOptimizationResult,
    DerivativeAuditResult,
    InverseProblemResult,
    NeopaxProfileAutodiffResult,
    NeopaxProfileUncertaintyResult,
    RobustBootstrapOptimizationResult,
    example_bootstrap_current_optimization,
    example_bootstrap_current_robust_optimization,
    example_derivative_audit,
    example_inverse_problem,
    example_neopax_profile_autodiff,
    example_neopax_profile_uncertainty,
)
from .booz import BoozmnSurface, load_boozmn_surface
from .config import configure_compilation_cache, enable_x64
from .convergence import (
    AdaptiveConvergenceResult,
    ConvergenceStep,
    solve_monoenergetic_converged,
)
from .database import (
    MonoenergeticDatabaseArrays,
    build_monoenergetic_database_arrays,
    stack_monoenergetic_database_arrays,
)
from .geometry import BoozerSurface, VmecSurface, example_surface
from .grids import GridSpec
from .inputfiles import (
    infer_run_output_format,
    load_run_config,
    load_run_output,
    run_from_input_file,
    save_run_output,
)
from .io import (
    load_boozer_modes_csv,
    load_dkes_surface,
    load_magnetic_configuration_surface,
    load_vmec_surface,
)
from .neopax import (
    DifferentiableNeopaxField,
    NeopaxMonoenergeticArrays,
    NeopaxScan,
    build_differentiable_neopax_field,
    build_differentiable_neopax_field_from_vmec_booz_files,
    build_differentiable_neopax_field_from_vmec_jax_boundary_params,
    build_differentiable_neopax_field_from_vmec_jax_state,
    build_ntx_neopax_scan,
    build_ntx_neopax_scan_from_surfaces,
    build_ntx_neopax_scan_from_vmec_jax_boundary_params,
    build_ntx_neopax_scan_from_vmec_jax_state,
    get_differentiable_neopax_fluxes,
    load_neopax_reference_scan,
    neopax_scan_requires_rebuild,
    scan_to_neopax_arrays,
    to_neopax_monoenergetic,
    write_neopax_scan_hdf5,
)
from .parallel import solve_monoenergetic_multiprocess_scan
from .physics_gates import (
    ANALYTICAL_GATES,
    ARTIFACT_GATES,
    PhysicsGate,
    PhysicsGateResult,
    evaluate_artifact_gates,
    physics_gate_registry,
)
from .plotting import plot_run_output
from .profiles import (
    AmbipolarProfileFamilyResult,
    AmbipolarProfileResult,
    MonoenergeticSpeciesProfile,
    PrimitiveProfileTransportIterationResult,
    PrimitiveSpeciesProfile,
    ProfileBasisControlSpec,
    ProfileBasisOptimizationResult,
    ProfileControlOptimizationResult,
    ProfileControlSpec,
    ProfileTransportClosureSpec,
    ProfileTransportIterationResult,
    advance_primitive_profile_transport,
    advance_profile_transport,
    ambipolar_residual_profile,
    apply_profile_basis_control,
    apply_profile_control,
    bootstrap_current_objective,
    build_species_profile_from_primitives,
    build_species_profiles_from_primitives,
    current_response_objective,
    evaluate_scan_channel,
    evaluate_species_current_response,
    evaluate_species_particle_flux,
    optimize_profile_basis_control,
    optimize_profile_control,
    primitive_profile_transport_loss,
    profile_transport_loss,
    solve_ambipolar_er_profile,
    solve_ambipolar_profile_family,
    solve_primitive_profile_transport_loop,
    solve_profile_transport_loop,
)
from .resolution import GeometryResolutionReport, geometry_resolution_report
from .solver import (
    CompiledPreparedScanSolver,
    CompiledPreparedSolver,
    MonoenergeticCase,
    PreparedMonoenergeticSystem,
    PreparedScanCompilationReport,
    ResidualAuditResult,
    TransportResult,
    audit_prepared_residuals,
    compile_prepared_scan_solver,
    compile_prepared_solver,
    healthy_parallel_device_count,
    local_parallel_device_count,
    prepare_monoenergetic_system,
    solve_monoenergetic,
    solve_monoenergetic_internal,
    solve_monoenergetic_parallel_scan,
    solve_monoenergetic_scan,
    solve_prepared,
    solve_prepared_coefficient_vector,
    solve_prepared_coefficient_vector_vjp,
    solve_prepared_internal,
)
from .transport import onsager_error
from .vmec_jax_backend import (
    VmecJaxBoundaryContext,
    build_vmec_jax_boundary_context,
    initial_guess_vmec_jax_boundary_state,
    relax_vmec_jax_boundary_state_explicit,
    solve_vmec_jax_boundary_state,
    surface_from_vmec_jax_state,
    surface_from_vmec_jax_wout,
)
from .vmec_jax_vmec import surface_from_vmec_jax_vmec_wout, surface_from_vmec_jax_vmec_wout_file

try:
    __version__ = version("ntx")
except PackageNotFoundError:
    __version__ = "0.2.4"

__all__ = [
    "__version__",
    "BoozmnSurface",
    "BoozerSurface",
    "AdaptiveConvergenceResult",
    "BootstrapOptimizationResult",
    "AmbipolarProfileFamilyResult",
    "AmbipolarProfileResult",
    "CompiledPreparedSolver",
    "CompiledPreparedScanSolver",
    "ConvergenceStep",
    "DerivativeAuditResult",
    "DifferentiableNeopaxField",
    "GridSpec",
    "GeometryResolutionReport",
    "MonoenergeticCase",
    "MonoenergeticDatabaseArrays",
    "MonoenergeticSpeciesProfile",
    "PhysicsGate",
    "PhysicsGateResult",
    "PrimitiveSpeciesProfile",
    "ProfileBasisControlSpec",
    "ProfileBasisOptimizationResult",
    "PrimitiveProfileTransportIterationResult",
    "ProfileTransportClosureSpec",
    "ProfileTransportIterationResult",
    "ProfileControlOptimizationResult",
    "ProfileControlSpec",
    "NeopaxMonoenergeticArrays",
    "NeopaxScan",
    "PreparedMonoenergeticSystem",
    "PreparedScanCompilationReport",
    "ResidualAuditResult",
    "TransportResult",
    "VmecJaxBoundaryContext",
    "VmecSurface",
    "ANALYTICAL_GATES",
    "ARTIFACT_GATES",
    "build_differentiable_neopax_field",
    "audit_prepared_residuals",
    "build_differentiable_neopax_field_from_vmec_booz_files",
    "build_differentiable_neopax_field_from_vmec_jax_boundary_params",
    "build_differentiable_neopax_field_from_vmec_jax_state",
    "build_vmec_jax_boundary_context",
    "initial_guess_vmec_jax_boundary_state",
    "build_monoenergetic_database_arrays",
    "build_ntx_neopax_scan",
    "build_ntx_neopax_scan_from_vmec_jax_boundary_params",
    "build_ntx_neopax_scan_from_vmec_jax_state",
    "build_ntx_neopax_scan_from_surfaces",
    "get_differentiable_neopax_fluxes",
    "geometry_resolution_report",
    "evaluate_scan_channel",
    "evaluate_species_current_response",
    "evaluate_species_particle_flux",
    "compile_prepared_solver",
    "compile_prepared_scan_solver",
    "configure_compilation_cache",
    "enable_x64",
    "example_derivative_audit",
    "example_surface",
    "example_bootstrap_current_optimization",
    "evaluate_artifact_gates",
    "infer_run_output_format",
    "load_boozmn_surface",
    "load_run_output",
    "load_run_config",
    "load_boozer_modes_csv",
    "load_dkes_surface",
    "load_magnetic_configuration_surface",
    "load_neopax_reference_scan",
    "neopax_scan_requires_rebuild",
    "load_vmec_surface",
    "healthy_parallel_device_count",
    "local_parallel_device_count",
    "onsager_error",
    "physics_gate_registry",
    "ambipolar_residual_profile",
    "advance_profile_transport",
    "advance_primitive_profile_transport",
    "apply_profile_basis_control",
    "apply_profile_control",
    "build_species_profile_from_primitives",
    "build_species_profiles_from_primitives",
    "bootstrap_current_objective",
    "current_response_objective",
    "prepare_monoenergetic_system",
    "plot_run_output",
    "run_from_input_file",
    "save_run_output",
    "scan_to_neopax_arrays",
    "solve_monoenergetic",
    "solve_monoenergetic_converged",
    "solve_monoenergetic_internal",
    "solve_monoenergetic_multiprocess_scan",
    "solve_monoenergetic_parallel_scan",
    "solve_monoenergetic_scan",
    "solve_prepared_coefficient_vector",
    "solve_prepared_coefficient_vector_vjp",
    "solve_prepared",
    "solve_prepared_internal",
    "stack_monoenergetic_database_arrays",
    "surface_from_vmec_jax_state",
    "surface_from_vmec_jax_wout",
    "surface_from_vmec_jax_vmec_wout",
    "surface_from_vmec_jax_vmec_wout_file",
    "relax_vmec_jax_boundary_state_explicit",
    "solve_vmec_jax_boundary_state",
    "solve_ambipolar_er_profile",
    "solve_ambipolar_profile_family",
    "optimize_profile_basis_control",
    "optimize_profile_control",
    "primitive_profile_transport_loss",
    "profile_transport_loss",
    "solve_primitive_profile_transport_loop",
    "to_neopax_monoenergetic",
    "write_neopax_scan_hdf5",
    "solve_profile_transport_loop",
    "InverseProblemResult",
    "NeopaxProfileAutodiffResult",
    "NeopaxProfileUncertaintyResult",
    "RobustBootstrapOptimizationResult",
    "example_inverse_problem",
    "example_neopax_profile_autodiff",
    "example_neopax_profile_uncertainty",
    "example_bootstrap_current_robust_optimization",
]
