"""Compatibility facade for scan execution and local-device sharding."""

from ._solver_core import prepare_monoenergetic_system
from ._solver_scan_core import solve_monoenergetic_scan, solve_scan
from ._solver_scan_execution import (
    SUPPORTED_SCAN_BATCH_SIZES,
    CompiledPreparedScanSolver,
    PreparedScanCompilationReport,
    ScanExecutionMode,
    _coefficients_dict,
    _is_out_of_memory_error,
    _memory_stat,
    _resolve_scan_execution_mode,
    _resolved_scan_inputs,
    _run_fixed_batch_scan,
    _scan_coefficients_batched,
    _scan_coefficients_sequential,
    _scan_coefficients_sequential_impl,
    _scan_coefficients_serial,
    _scan_coefficients_vectorized,
    _scan_coefficients_vectorized_impl,
    _solve_scan_point,
    compile_prepared_scan_solver,
)
from ._solver_scan_parallel import (
    _healthy_parallel_devices_cached,
    healthy_parallel_device_count,
    healthy_parallel_devices,
    local_parallel_device_count,
    solve_monoenergetic_parallel_scan,
)

__all__ = [
    "SUPPORTED_SCAN_BATCH_SIZES",
    "CompiledPreparedScanSolver",
    "PreparedScanCompilationReport",
    "ScanExecutionMode",
    "compile_prepared_scan_solver",
    "healthy_parallel_device_count",
    "healthy_parallel_devices",
    "local_parallel_device_count",
    "prepare_monoenergetic_system",
    "solve_monoenergetic_parallel_scan",
    "solve_monoenergetic_scan",
    "solve_scan",
    "_coefficients_dict",
    "_healthy_parallel_devices_cached",
    "_is_out_of_memory_error",
    "_memory_stat",
    "_resolve_scan_execution_mode",
    "_resolved_scan_inputs",
    "_run_fixed_batch_scan",
    "_scan_coefficients_batched",
    "_scan_coefficients_sequential",
    "_scan_coefficients_sequential_impl",
    "_scan_coefficients_serial",
    "_scan_coefficients_vectorized",
    "_scan_coefficients_vectorized_impl",
    "_solve_scan_point",
]
